### PR TITLE
671:  Switch sca_capital_projects to use sca_capacity_projects

### PR DESCRIPTION
**Pull request by bfreeds**
This PR addresses #671 by:
- Updates table name (`sca_capital_projects` => `sca_capacity_projects`)
- Updates changing schema (renames sca capacity projects' `project_dsf` to `uid`)
- Updates Public Schools "No Action Scenario" UI
  - We no longer need to show the user "% Funded", as we assume all `sca_capacity_projects` are funded enough to be included in analysis.  

Part of #484

### CODE REVIEW

**Comment by bfreeds** [comment]
#### Manual Database Steps
Here are the manual steps taken to align previous 2 versions of `sca_capital_projects` to the new schema of `sca_capacity_projects`.  Documenting for posterity.

1.  Copied `sca_capital_projects` from `ceqr_data` database into `ceqr_data_staging`
     - Using pg_dump from `ceqr_data`, then loading with psql into `ceqr_data_staging`
1. Altered table schemas in ceqr_data_staging
   ```sql
   ALTER TABLE sca_capital_projects."2018" SET SCHEMA sca_capacity_projects;
   ALTER TABLE sca_capital_projects."022019" SET SCHEMA sca_capacity_projects;

    -- then drop old schema
   DROP SCHEMA sca_capital projects;
   ```
1. RenamedEDMs published `sca_capacity_projects.latest` to document version
   ```sql
   ALTER TABLE sca_capacity_projects.latest RENAME TO "112019";
   ```
1. Dropped `project_dsf` columns
   ```sql
   ALTER TABLE sca_capacity_projects."2018" DROP COLUMN project_dsf;
   ALTER TABLE sca_capacity_projects."022019" DROP COLUMN project_dsf;
   ```

**Comment by bfreeds** [comment]
After learning that `project_dsf` was being used in the app to determine when to load new projects, reached out to EDM to find a unique identifier on the tables. 

From EDM:
> We added a uid field to sca_capaicty_projects, which is reflected in the "latest" table under the sca_capacity_projects schema in the EDM publication database.  The logic for creating the uid field is [here](https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNYCPlanning%2Fceqr-app-data%2Fblob%2Fmaster%2Fceqr%2Frecipes%2Fsca_capacity_projects%2Fbuild.py&data=02%7C01%7CBFriedly%40planning.nyc.gov%7C9821f92f7c314ab498ed08d7d0ce368f%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C637207456403227305&sdata=9R6FxKWUdxHoiiqSCC8%2FIhrYTfnrDfGnXFfDCawQrbM%3D&reserved=0).  

This added a unique ID to the new dataset.  

Here's the SQL I used to align previous datasets to use the same data schema as this new EDM dataset:
```sql
-- start transaction block
begin;
    -- change schemas to new schema
    ALTER TABLE sca_capital_projects."2018" SET SCHEMA sca_capacity_projects;
    ALTER TABLE sca_capital_projects."022019" SET SCHEMA sca_capacity_projects;
    DROP SCHEMA sca_capital_projects CASCADE; -- cleanup unused schema

    -- update project_dsf column to "uid" to follow edm data schema
    ALTER TABLE sca_capacity_projects."2018" RENAME COLUMN project_dsf TO uid;
    ALTER TABLE sca_capacity_projects."022019" RENAME COLUMN project_dsf TO uid;
    -- align data type to follow edm's
    ALTER TABLE sca_capacity_projects."2018"
        ALTER COLUMN uid SET DATA TYPE text;
    ALTER TABLE sca_capacity_projects."022019"
        ALTER COLUMN uid SET DATA TYPE text;

commit; -- commit transaction block if no errors
```

For old datasets, I changed the `project_dsf` column to align with the new `uid` column.  Though EDM uses a hash method to generate unique values, I just kept the values for `project_dsf` since we know these are unique and previous analyses have these values stored on their model.  

To update previous public schools analyses in the database to follow this change in data schema, will need to **create a database migration** that updates existing projects `project_dsf` to be called `uid`.

**Comment by allthesignals** [comment]
This is a draft PR but do we need it for anything?

**Comment by bfreeds** [comment]
@allthesignals All the work in this branch was merged with the `update-public-schools-schema` branch.  Only use of this is documenting some steps taken on the database.  Closing.

**Pull request closed without merging**
